### ISSUE TITLE
Pre-Release Todo

### ISSUE THREAD

**Issue by bsaund** [UM-ARM-Lab/mps_shape_completion#1]
- [x] Docker container with prerequisites
- [x] Add tests for Continuous Integration
- [x] Continuous Integration (Docker, yaml, travis)
- [ ]  ~Docker container that has this pre-built, for ros deployment (stretch)~
- [x] Update Readme (purpose, build instruction, run instruction)
- [x] Simple example/test
- [x] Store pretrained model in a long term accessible directory
- [ ] ~Store full model in one place. Currently the model data is stored on google drive, the .index and .meta are store in git~
- [x] Change paths in python code to find files relative to ros packages. Basically, review all `***_path` python variables

**Comment by bsaund** [comment]
Migrated from https://github.com/UM-ARM-Lab/Shape-Completion-API/issues/4

**Comment by bsaund** [comment]
@a-price @jinlinyi  The model is currently stored on a umich google drive. 
Do you know who owns this? When Linyi graduates, will this disappear?

**Comment by bsaund** [comment]
I moved the model to my google drive.

I am moving on for now.
Next Steps
- [ ] Better unit tests. Currently this just tests that the demo creates _some_ output.binvox
- [ ] Better home for data file. git lfs? armlab google drive?
